### ISSUE TITLE
Feature: unwrap single option for select component

### ISSUE THREAD

**Issue by lawvs** [zodui/zodui#24]
This library is excellent. Thank you for your contribution.

It's a common requirement to allow users to select from multiple options in a form.

I use the following schema to define the form I need.

```ts
import * as z from 'zod'

export default z
  .object({
    test: z.literal("a")
      .or(z.literal("b"))
      .or(z.literal("c"))
      .or(z.literal("d"))
  })
```

However, zodui doesn't generate the expected select with all the options. 

![Screenshot 2024-02-23 at 20 01 40](https://github.com/zodui/zodui/assets/18554747/09fe6210-360c-4790-b00e-b32116d7372f)

**Comment by NWYLZW** [comment]
This data of type is based on zod, but the 'or' operation in zod doesn't seem to work as I expected. I need to handle it differently, sorry.

**Comment by lawvs** [comment]
I have discovered that the issue is caused by the coding style.

```ts
z.literal("a")
  .or(z.literal("b"))
  .or(z.literal("c"))
// (a || b) || c

z.union([z.literal("a"), z.literal("b"), z.literal("c")])
// a || b || c
```

The Union style works as expected in the Zodui.

<img width="391" alt="Screenshot 2024-02-25 at 18 08 49" src="https://github.com/zodui/zodui/assets/18554747/0a9649cf-6392-4a57-9888-43f5056e65cb">

**Comment by NWYLZW** [comment]
I indeed didn't test and consider this scenario. In a way, it is indeed a coding style issue. However, I believe I should support the 'or' operation, but I didn't initially realize that the resulting type from this operation is not similar to the union operation, but rather has some differences.
For now, users encountering this issue can convert it to the style of `union([])`. However, in the future, I will handle this situation separately.
